version: '3.4'
services:
    db:
        image: mysql-spring-rest
        command: mysqld --default-authentication-plugin=mysql_native_password
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        environment: 
            TZ: America/Sao_Paulo
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_DATABASE: ioq_rest
        ports:
            - "3306:3306"
        networks: 
            - spring-network 
    rest-spring-api:
        image: api-spring-rest
        restart: always
        build: ./IOQApplication
        working_dir: /IOQApplication
        environment: 
            TZ: America/Sao_Paulo
            SPRING_BOOT_ENVIRONMENT: production
        volumes: 
            - ./IOQApplication:/IOQApplication
            - ~/.m2:/root/.m2
        ports: 
            - "8080:8080"
        command: mvn clean spring-boot:run
        links: 
            - db
        depends_on: 
            - db
        networks: 
            - spring-network
networks: 
    spring-network:
        driver: bridge